# /etc/dracut-ukify.conf
# Unified UKI generation config file for Arch Linux hooks

[Box]
# Your visual bootsplash definition asset
Splash=/usr/share/systemd/bootctl/splash-arch.bmp

[Signing]
# Your cryptographic Secure Boot enrollment targets
SecureBootSigningCert=/usr/share/secureboot/keys/db/db.pem
SecureBootSigningKey=/usr/share/secureboot/keys/db/db.key

[Target]
Cmdline=rw \
	rd.auto=1 \
	root=UUID={{ .system.storage.root_uuid }} \
	resume=UUID={{ .system.storage.root_uuid }} \
	rootflags=subvol=@ \
	mem_encrypt=off \
	apparmor=1 \
	security=apparmor \
	rd.vconsole.font=ter-120n \
	rd.info \
{{- if .system.hw.tpm }}
	rd.luks.uuid=luks-{{ .system.storage.luks_uuid }} \
	rd.luks.options=tpm2-device=auto,tpm2-with-pin=true,discard
{{- else }}
	rd.luks.options=discard
{{- end }}
