[".local/share/fonts/Meslo"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.tar.xz"
    #exact = true
    #stripComponents = 1
    refreshPeriod = "168h"
    checksum.sha512 = "5364b31502e54884e4dc0dac61e19c026cfac5b1f9a02053d57ecdba2ec249851e2766f252952ff3afdf51ca59bc705422715f6942836312333f6b2000e3402a"

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/tmux-sensible/sensible.tmux"]
    type = "file"
    url = "https://raw.githubusercontent.com/tmux-plugins/tmux-sensible/master/sensible.tmux"
    refreshPeriod = "168h"

[".local/bin/bitwarden-x86_64.appimage"]
    type = "file"
    executable = true
    url = "https://vault.bitwarden.com/download/?app=desktop&platform=linux"
    refreshPeriod = "168h"

[".asdf"]
    type = "archive"
    url = "https://codeload.github.com/asdf-vm/asdf/tar.gz/refs/tags/v0.14.0"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
