# ~/.config/sway/config.d/01_outputs.conf
# SwayWM outputs configuration. For detailed information type "man sway-output"

# Default wallpaper
output * bg #24273a solid_color

# Dynamically include host-specific display layouts if they exist
include outputs.d/$(cat /etc/hostname)
