# Status Bar: waybar
#
# Read `man 5 sway-bar` for more information about this section.
# Read `man 5 waybar` for more information about the waybar instance style and layout configuration
#
# Requires: waybar

exec_always sh -c 'if [[ "$(hostname)" == *iceberg* ]]; then killall waybar; waybar -c $HOME/.config/waybar/iceberg-config.jsonc -s $HOME/.config/waybar/iceberg-style.css; else killall waybar; waybar -c $HOME/.config/waybar/config.jsonc -s $HOME/.config/waybar/style.css; fi'
