[main]
summary=Forces Intel i7-8550U to maintain maximum frequencies and prevents downclocking.
include=throughput-performance

[cpu]
governor=performance
energy_perf_bias=performance
energy_performance_preference=performance
min_perf_pct=100
boost=1

[video]
blank_screen=true
