# vim: filetype=fish
# .config/fish/conf.d/aliases.fish

# 1. Define the single source of truth path
set -l bash_aliases "$HOME/.bashrc.d/80_aliases"

if test -f $bash_aliases
    # 2. Source the shared core aliases generated by Chezmoi
    source $bash_aliases

    # 3. Cleanly override the few items that break in Fish
    alias cdr='cd -P .'

    function h; history | grep $argv; end
    function f; find . | grep $argv; end
    function p; ps aux | grep $argv; end
end
