# -------------------------------------------------------------
# Global Default Settings (Fallbacks)
# -------------------------------------------------------------
port = /dev/ttyUSB0
databits = 8
parity = none
stopbits = 1

# -------------------------------------------------------------
# Profile: 9600 (Legacy or Low-Speed Devices) (Cisco)
# -------------------------------------------------------------
[9600]
baud = 9600

# -------------------------------------------------------------
# Profile: 115200 (Modern or High-Speed Devices) (Ubiquti)
# -------------------------------------------------------------
[115200]
baud = 115200
